### ISSUE TITLE
warnings and notices on multisite plugin upload screen

### ISSUE THREAD

**Issue by lkraav** [mainwp/mainwp#10]
https://yourmultisite.com/wp-admin/network/plugin-install.php?tab=upload

    WARNING: wp-content/plugins/mainwp/page/MainWPAPISettings.page.php:200 - Illegal string offset 'slugs'
    require('wp-admin/plugin-install.php'), include('wp-admin/admin-header.php'), do_action('in_admin_header'), call_user_func_array, wp_admin_bar_render, do_action_ref_array, call_user_func_array, wp_admin_bar_updates_menu, wp_get_update_data, wp_update_plugins, set_site_transient, apply_filters('pre_set_site_transient_update_plugins'), call_user_func_array, MainWPSystem->pre_check_update_custom, MainWPSystem->checkUpgrade, MainWPAPISettings::checkUpgrade

    WARNING: wp-content/plugins/mainwp/page/MainWPAPISettings.page.php:201 - Illegal string offset 'am_slugs'
    require('wp-admin/plugin-install.php'), include('wp-admin/admin-header.php'), do_action('in_admin_header'), call_user_func_array, wp_admin_bar_render, do_action_ref_array, call_user_func_array, wp_admin_bar_updates_menu, wp_get_update_data, wp_update_plugins, set_site_transient, apply_filters('pre_set_site_transient_update_plugins'), call_user_func_array, MainWPSystem->pre_check_update_custom, MainWPSystem->checkUpgrade, MainWPAPISettings::checkUpgrade

    NOTICE: wp-content/plugins/mainwp/page/MainWPAPISettings.page.php:200 - Uninitialized string offset: 0
    require('wp-admin/plugin-install.php'), include('wp-admin/admin-header.php'), do_action('in_admin_header'), call_user_func_array, wp_admin_bar_render, do_action_ref_array, call_user_func_array, wp_admin_bar_updates_menu, wp_get_update_data, wp_update_plugins, set_site_transient, apply_filters('pre_set_site_transient_update_plugins'), call_user_func_array, MainWPSystem->pre_check_update_custom, MainWPSystem->checkUpgrade, MainWPAPISettings::checkUpgrade

    NOTICE: wp-content/plugins/mainwp/page/MainWPAPISettings.page.php:201 - Uninitialized string offset: 0
    require('wp-admin/plugin-install.php'), include('wp-admin/admin-header.php'), do_action('in_admin_header'), call_user_func_array, wp_admin_bar_render, do_action_ref_array, call_user_func_array, wp_admin_bar_updates_menu, wp_get_update_data, wp_update_plugins, set_site_transient, apply_filters('pre_set_site_transient_update_plugins'), call_user_func_array, MainWPSystem->pre_check_update_custom, MainWPSystem->checkUpgrade, MainWPAPISettings::checkUpgrade

    NOTICE: wp-content/plugins/mainwp/page/MainWPMain.page.php:29 - Undefined property: MainWPMain::$dashBoard
    require('wp-admin/plugin-install.php'), include('wp-admin/admin-header.php'), WP_Screen->render_screen_meta, apply_filters('screen_layout_columns'), call_user_func_array, MainWPMain->on_screen_layout_columns

**Comment by ruben-** [comment]
Fixed in v3.0
