### ISSUE TITLE
[i18n] Bad pluralization of strings

### ISSUE THREAD

**Issue by pedro-mendonca** [mainwp/mainwp#100]
The plugin have a lot of bad i18n strings, specifically plurals and lack of context.

This is a short case, there are some more plurals like this one, with an hardcoded extra 's':
https://github.com/mainwp/mainwp/blob/master/widget/widget-mainwp-right-now.php#L1617
```<?php echo esc_attr($cnt); ?> <?php _e( 'Update', 'mainwp' ); ?><?php echo( $cnt > 1 ? 's' : '' ); ?>```

Adding an 's' in case of >1 is just plain wrong. This sould be made a _n() gettext string.

**Comment by bogdan-mainwp** [comment]
Resolved in version 4

For any further assistance, please feel free to open a [helpdesk ticket](https://mainwp.com/my-account/get-support/).
