### ISSUE TITLE
Suggestion: Auto Update from Favourites Extension Source Option

### ISSUE THREAD

**Issue by lesliechw** [mainwp/mainwp#102]
Hi Dev,

I would like to suggest to have the auto update options of "Plugin Automatic Daily Update" to have additional option of "Plugin Automatic Daily Update from Favourites Source".

With that will have much more control over the version and updates.

With that, Favourites Extension will act as Plugins Update Central Source for your network of WordPress.

With that, the network maintainer only need to worry about upload plugins of latest version, but not need to update child site that use the plugin manually.

**Comment by bogdan-mainwp** [comment]
Hi @lesliechw, thanks for reaching out and sending us your feature request. We already have this feature request on our Trello board. Please feel free to check our [boards](https://mainwp.com/mainwp-roadmaps/) and vote/comment features that you like.
