### ISSUE TITLE
Advanced Uptime Monitor create Monitor Error

### ISSUE THREAD

**Issue by lesliechw** [mainwp/mainwp#103]
When try to "Create monitors for all Chile Sites", I got error [ ERROR: "alert_contacts" is not valid ].

When "Add New Monitor" to create monitor for single site, no problem.

Please advice how to fix this. Thanks.

**Comment by bogdan-mainwp** [comment]
Hi @lesliechw, can you please try to hard-refresh your browser a couple of times and see if that helps, if not please open a [helpdesk ticket](https://mainwp.com/support) so we can look into this.

**Comment by bogdan-mainwp** [comment]
Hi @lesliechw, since we haven't heard anything about his problem and we can't duplicate it with the latest version of the AUM extension, we will consider this problem resolved. 

For any further assistance, please feel free to ope a [helpdesk ticket](https://mainwp.com/my-account/get-support/).
