### ISSUE TITLE
MainWP > Sites > Manage Sites : CSS problem ? All rows are blank but child sites are in the HTML source.

### ISSUE THREAD

**Issue by 0xTHMS** [mainwp/mainwp#112]
Hi.

We are using MainWP Dashboard version 4.0.5 on Wordpress 5.3
The problem appeared before, when we were using Wordpress 5.2

When we go to the MainWP > Sites > Manage Sites view, the HTML table is empty, but if I look at the source code, I see that my child sites are here.

![2019-11-26-174002_1915x585_scrot](https://user-images.githubusercontent.com/7324626/69653637-d63fa480-1073-11ea-90c0-cd25a7123465.png)

Any idea how to solve this problem ?

**Comment by bogdan-mainwp** [comment]
Hi @0xTHMS, I have never seen this issue. Can you please open a helpdesk ticket so we can check this out?

**Comment by 0xTHMS** [comment]
Of course I did not know about an helpdesk.
I'm opening an issue.

**Comment by 0xTHMS** [comment]
Issue opened.
