### ISSUE TITLE
Use REST API instead of wp ajax for child site connectivity

### ISSUE THREAD

**Issue by binaryfire** [mainwp/mainwp#113]
Hi guys,

Would it be possible to move from using wp ajax to custom REST API endpoints for child site connectivity / control? Would be a little faster and it would allow for much more modern authentication methods like JWT

I'm assuming all you'd need to do is build a custom REST API endpoint in the child plugin and implement authentication. The dashboard and extensions would only need some minor tweaking to point them to the new data source.

**Comment by dennisdornon** [comment]
After talking to our team changing from WP AJAX to REST API is not something that we can do right now. 

This would require full refactoring and we are not sure that we could keep all the functionality already baked in. 

So for the time being we need to stay with AJAX. 

If you are concerned about security with the current system, we believe that the OpenSSL encrypted communication along with the additional hardenings is pretty secure. 

Please note: that we have our plugin constantly reviewed by security experts on hackerone.com to keep the system as secure as possible.
