### ISSUE TITLE
"Plugin Automatic Update Trust List" search only searches through paging-visible plugins

### ISSUE THREAD

**Issue by lkraav** [mainwp/mainwp#12]
2.0.10

When loading https://site.com/wp-admin/admin.php?page=PluginsAutoUpdate and the plugin list is empty, the search box will not find anything.

The only option to work with the screen is to maximize the paging to 40 items and manually find the plugin you want to adjust.

**Comment by dennisdornon** [comment]
That's not something I am able reproduce on any of our test sites.  When I run a search for a specific plugin when no plugins are listed yet it returns just the plugin I was looking for. 

Do you have a example search query you were using?

**Comment by lkraav** [comment]
Perhaps it's relevant this is happening on multisite installation, and the dashboard is installed on the master site (ID 1)

**Comment by dennisdornon** [comment]
I don't believe that should matter but if you want to open a ticket in the [MainWP Support Portal](http://support.mainwp.com/support/home) I'll be happy to take a look.

**Comment by lkraav** [comment]
I've narrowed the problem down somewhat. It's the `if (get_option('mainwp_optimize') == 1)` logic branch in `renderAllActiveTable()`.

If I turn the optimize functionality OFF in settings, then plugin list loads immediately, and plugin keyword queries also work.

**Comment by ruben-** [comment]
Fixed in v3.0
