### ISSUE TITLE
Reconnect issue

### ISSUE THREAD

**Issue by JosefJezek** [mainwp/mainwp#13]
I can't reconnect to child when child after deactivate-activate have new Security ID. I set new id.

**Comment by dennisdornon** [comment]
Please try the steps below to clear everything out of MainWP and then re-add.  If that doesn't help please open a ticket at the [MainWP Support Portal](http://support.mainwp.com)

Step 1.  Delete the Child site from your MainWP Dashboard 
Step 2.  Disable the Child Plugin on Child Site
Step 3.  With the Child disabled try to re-add the Child site to the Dashboard (You should get an error that no MainWP is detected) 
Step 4.  Enable the Child Plugin on the Child Site
Step 5.  Re-add the Child site to your Dashboard (It should connect without issue this time)
