### ISSUE TITLE
database query audit

### ISSUE THREAD

**Issue by ctalkington** [mainwp/mainwp#14]
ive been using mainwp for sometime and one thing that bugs me as a developer is the amount of queries that it runs on every load; some are get_option which being that mainwp is meant to be run on its own install can be set as `autoload` but aren't so instead we go out to the database 10+ times to get these.

I have a few examples of just how out of control the queries are; mainly taken from the mainwp dashboard of two sites.

A: Managing 10 Sites
Dashboard Queries: 270 (0.0595ms)

B: Managing 60 Sites
Dashboard Queries: 2,210 (0.1072ms)

The bulk of these come from the calling of a few options per site, can we not combine some queries to be smarter about our usage and help it scale better? I get that most database servers don't have much an issue but that's a lot of queries that could be optimized to everyones benefit.

Of course using something like object cache would reduce load but really shouldn't be required if a little more thought was put into how things are pulled.

**Comment by dennisdornon** [comment]
Thanks we are reviewing that for the next update.

**Comment by khromov** [comment]
Adding a few from this thread:
https://wordpress.org/support/topic/performance-issues-10

```
mainwp_child_server
mainwp_backupwordpress_ext_enabled
```

**Comment by ruben-** [comment]
Queries are fixed in latest version.
