### ISSUE TITLE
Encoding mistake in single plugin update modal

### ISSUE THREAD

**Issue by rtpHarry** [mainwp/mainwp#15]
I noticed when I updated a single plugin in the mainwp admin panel that has spaces in it they are displayed still encoded as +

![image](https://cloud.githubusercontent.com/assets/1038062/7783780/1b0b0e7a-0146-11e5-8392-8b0daad8b973.png)

**Comment by ctalkington** [comment]
ive also noticed this.

**Comment by ruben-** [comment]
Fixed in v3.0
