### ISSUE TITLE
wp-cli-0.19.1: Undefined index: pagenow in wp-includes/link-template.php

### ISSUE THREAD

**Issue by lkraav** [mainwp/mainwp#16]
The most basic wp-cli info command (and all others) cause this notice. Perhaps MainWP should check whether it's actually being loaded in /wp-admin/ before running its logic, since it may not be relevant when loaded over command line. global $pagenow is listed here https://codex.wordpress.org/Global_Variables#Admin_Globals

```
$ [-] wp help
PHP Notice:  Undefined index: pagenow in /home/warmpress/wp-includes/link-template.php on line 2695
PHP Stack trace:
PHP   1. {main}() /home/leho/wp-cli/php/boot-fs.php:0
PHP   2. include() /home/leho/wp-cli/php/boot-fs.php:17
PHP   3. require() /home/leho/wp-cli/php/wp-cli.php:26
PHP   4. include_once() /home/leho/wp-cli/php/wp-settings-cli.php:233
PHP   5. MainWPSystem->__construct() wp-content/plugins/mainwp/mainwp.php:66
PHP   6. MainWPAPISettings::testAPIs() wp-content/plugins/mainwp/class/MainWPSystem.class.php:66
PHP   7. get_home_url() wp-content/plugins/mainwp/page/MainWPAPISettings.page.php:112
```

**Comment by szepeviktor** [comment]
Similar: https://github.com/wp-cli/wp-cli/issues/1983

**Comment by ruben-** [comment]
The method causing this is removed in v3.0-beta. The help method of wp-cli (0.22 at this moment) is working fine with MainWP v3.0-beta installed. (soon to be released final)
