### ISSUE TITLE
admin scripts and styles should be enqueued

### ISSUE THREAD

**Issue by ctalkington** [mainwp/mainwp#17]
there is quite a bit of raw script and styles output going on in the admin. these should use the proper enqueue methods offered by WordPress.

using such enqueue methods offers the ability to append version string which helps with cache busting. the need for this becomes apparent when the ui blows up after upgrades until you force clear cache.

https://developer.wordpress.org/reference/hooks/admin_enqueue_scripts/

**Comment by ctalkington** [comment]
see #18. closing this out in favor of PR.

**Comment by ruben-** [comment]
I've modified this in the past, but we noticed a lot of issues with the
order the JS was included so we rolled back to this. The only fix then was
to add the real script tags. We will retest your commit to see if
everything works on the newer versions of WP with the enqueue_scripts.

On Thu, Jun 11, 2015 at 12:16 AM, Chris Talkington <notifications@github.com
