### ISSUE TITLE
MainWP mails for theme conflicts that are ignored

### ISSUE THREAD

**Issue by tersmitten** [mainwp/mainwp#22]
> Hello MainWP User!

> We noticed the following updates are available on your MainWP Dashboard. (http://mainwp.foo.bar)
WordPress Theme Conflicts
> * foo.bar.nl-www -
> * bar.foo.com-www -

It would be nice if MainWP would check that updated are not ignored, before sending a mail

**Comment by tersmitten** [comment]
Anyone?

**Comment by dennisdornon** [comment]
Apologies, was there a question?  I was looking at this as more of a suggestion which has been noted.

**Comment by tersmitten** [comment]
Sorry that was probably my fault. I thought of it more as a bug since we get lots of unnecessary mail.

**Comment by ruben-** [comment]
Changed in v3.0
