### ISSUE TITLE
Translation issues

### ISSUE THREAD

**Issue by chland** [mainwp/mainwp#25]
I installed MainWP for the first time today and while I really like it, i encountered a rather annoying problem - i'm using the plugin on a site using the german language-file (which is pretty badly translated - but thats another story) and after seeing that quiet a lot of translations were missing, i fired up PoEdit and tried to translate the missing stuff on my own and fix the current translation.

Thats were i ran into quite a few "problems":

* a lot of strings are missing from the current PO-files (which can easily be fixed using PoEdits "Update from sources"-feature)
* the YES/NO checkboxes seem to pull their captions from the CSS files -> https://github.com/mainwp/mainwp/blob/master/css/mainwp.css#L1416
* a lot of the __/_e/etc. functions (i found roughly 80+) are missing proper text-domains 
* the plugin is "piecing together" some messages (some examples: https://github.com/mainwp/mainwp/blob/master/widget/widget-mainwp-right-now.php#L513 or https://github.com/mainwp/mainwp/blob/master/widget/widget-mainwp-right-now.php#L1636-L1638)
* Singular/Plural is handled manually instead of using _n() -> https://github.com/mainwp/mainwp/blob/master/widget/widget-mainwp-right-now.php#L1445-L1447
* there are quite a lot of nearly identical strings in the language files where the only difference is a trailing "." -> for example "Please enter csv file for upload" vs. "Please enter csv file for upload.", "Not updated yet" vs. "Not updated yet.", etc.

It would be nice if those things could be resolved in an upcoming release, because following WordPress's "Best Practices" (https://codex.wordpress.org/I18n_for_WordPress_Developers) makes it a lot easier to translate the plugin (not to mention that getting rid of duplicate strings reduces the memory-load, etc.).

**Comment by dennisdornon** [comment]
Thanks for your feedback. I won't be able to get those changes in the next version, since we are on the final testing for that release, but I will priority translation in the update after this one.

**Comment by ctalkington** [comment]
you could also adopt a build system such as grunt and use `wp-i18n` which as tasks for updating/adding missing text domains.

https://github.com/cedaro/grunt-wp-i18n

**Comment by ruben-** [comment]
Reviewed in v3.0
