### ISSUE TITLE
Site Import assumes use of return character

### ISSUE THREAD

**Issue by pcfreak30** [mainwp/mainwp#257]
When importing sites, `\MainWP_Manage_Sites_View::renderImportSites` runs `$lines = explode( "\r\n", $content ); // PHP_EOL` which assumes a windows formatted file. this is a bad assumption on compatibility with mac, windows and linux.

To convert all three should replace `\r\n` and then `\r` with `\n`, then split on that.

**Comment by bogdan-mainwp** [comment]
Hi @pcfreak30, thanks for reporting this problem. 

I will have our dev team check this as soon as possible.

**Comment by bogdan-mainwp** [comment]
The dev team tweaked this and the update will be released in the next version.
