### ISSUE TITLE
MainWP_DB::install() always runs wizard, locks out admin with set_transient() "_mainwp_activation_redirect"

### ISSUE THREAD

**Issue by lkraav** [mainwp/mainwp#26]
I'm running PHP 7.0.2 + phpredis php7 branch for object cache. Multi-site. Disabling object cache didn't seem to make any difference to this problem.

Since 3.0, `MainWP_DB::install()` shows that `$currentVersion` is always empty.

This causes the installation wizard to always run, locking out the main site admin where I have `mainwp` activated.

Tested this:
```
$ wp delete transient _mainwp_activation_redirect
Successfully deleted.
$ wp get transient _mainwp_activation_redirect
1
```

We can see the transient is always set on every load, even if it's deleted before.

EDIT
Inserted a simple debugging statement in `install()` like this `error_log( "install(): " . var_export( $currentVersion, true ) );
`

```
[16-Jan-2016 22:11:01 UTC] install(): false
[16-Jan-2016 22:11:01 UTC] install(): false
```

**Comment by ruben-** [comment]
Could you please verify if this is fixed with the database class I just commited to the main branch?

**Comment by lkraav** [comment]
"Not right now" button works properly now, I'm able to continue browsing the main site without issues. Looks fixed.
