### ISSUE TITLE
Add child sites via CLI

### ISSUE THREAD

**Issue by marco-springer** [mainwp/mainwp#30]
I've just seen you are planning to add new CLI functionalities to MainWP [here](https://github.com/mainwp/mainwp/blob/f10164af6530c37b0912298eb5a341cd3af26b4a/class/class-mainwp-wp-cli-command.php#L28)

` * @todo: allow to add or remove child sites `

I'm really interested in using that functionality and wanted to ask if you already have a schedule for implementing it or if it will be done further ahead?

**Comment by ruben-** [comment]
We will be releasing this version soon with only limited functionality for CLI: syncing clients and updating themes/plugins.

In the next releases we will be adding new features to CLI depending on the response/requests of the users. Adding and removing child sites will be added in the second version containing CLI.

**Comment by thms0** [comment]
That would be a great addition, indeed.

**Comment by diroots** [comment]
Hello there, this answer was from 2016, more than 2 years ago. Is there any news nowadays?
