### ISSUE TITLE
cron/updatescheck.php error 500

### ISSUE THREAD

**Issue by reeslo** [mainwp/mainwp#31]
cron/bootstrap.php include wp-load.php from root directory.
In most case wp-load.php is located at the root folder.
When wordpress are installed in subdirectory (https://deliciousbrains.com/install-wordpress-subdirectory-composer-git-submodule/), this script does not work.

I have no idea for now how to get the real directory where wp-load.php are located. 

```
PHP Warning:  include_once(/var/www/wp-content/plugins/mainwp/cron/../../../../wp-load.php): failed to open stream: No such file or directory in /var/www/wp-content/plugins/mainwp/cron/bootstrap.php on line 10
PHP Warning:  include_once(): Failed opening '/var/www/wp-content/plugins/mainwp/cron/../../../../wp-load.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/wp-content/plugins/mainwp/cron/bootstrap.php on line 10
PHP Notice:  Undefined variable: mainWP in /var/www/wp-content/plugins/mainwp/cron/updatescheck.php on line 4
PHP Fatal error:  Call to a member function mainwp_cronupdatescheck_action() on null in /var/www/wp-content/plugins/mainwp/cron/updatescheck.php on line 4


```

**Comment by ruben-** [comment]
Could you test with the new bootstrap.php committed in the master branch?

**Comment by reeslo** [comment]
Does not work for me, if you check wp-load.php, it find parent folder to include wp-config.php.
I submited a pull request, with a glob to find into root sub-folders wp-load.php to include if found.

**Comment by ruben-** [comment]
You linked the setup in the first post. This setup has wp-config.php in the root directory, in this config your ABSPATH is defined with the subfolder. So normally the code I added gets the new ABSPATH and includes the wp-load.

What was not working with that approach?

The reason I'm asking: your pull requests searches all subfolders, so when you have multiple wordpress sites set up it could cause issues.

**Comment by reeslo** [comment]
Oh sorry, I drop this link without see the wp-config.php.

I use this approach http://www.24joursdeweb.fr/2014/comment-bien-versionner-son-site-wordpress-avec-git-et-github/ 

but I can set ABSPATH think this has no effect for my setup. I will retry it tomorrow at work. :)

**Comment by reeslo** [comment]
It's works !
