### ISSUE TITLE
Main Dashboard "Connection Status" Widget: Zero disconnected sites count in green color

### ISSUE THREAD

**Issue by dev-masta** [mainwp/mainwp#324]
**Is your feature request related to a problem? Please describe.**
I didn't use MainWP in almost a year - good work!
The new styling is much better than the one I saw last time, but - my entire Dashboard is now white and green, except the Disconnected Sites count, which is 0, but still in red.

![image](https://user-images.githubusercontent.com/3306507/82855755-7899f100-9f0c-11ea-809d-7b3a68f0df3b.png)

**Describe the solution you'd like**
I would like to have that number red if the count is greater than 0.
But if there are no disconnected child sites, then everything is ok, so it should be green to match the rest of the numbers and buttons.

**Describe alternatives you've considered**
I've tried cloning the repo and I couldn't find an obvious way to do it myself and create a PR.
But I'm willing to do it if someone could point me in the right direction so I don't spend a lot of time on it.

**Comment by bogdan-mainwp** [comment]
Hi @dev-masta, thanks for opening this issue and reporting this problem. Our dev team tweaked this and the update will be released in the next version.
