### ISSUE TITLE
MainWP Dashboard - Nginx Error Log

### ISSUE THREAD

**Issue by wrrr** [mainwp/mainwp#33]
2016/02/17 13:42:11 [error] 51578#0: *1587 FastCGI sent in stderr: "PHP message: PHP Warning:  array_splice() expects parameter 1 to be array, string given in /srv/http/mydomain/wp-content/plugins/mainwp-child/class/class-mainwp-child-themes-check.php on line 168
PHP message: PHP Warning:  Invalid argument supplied for foreach() in /srv/http/mydomain/wp-content/plugins/mainwp-child/class/class-mainwp-child-themes-check.php on line 170" while reading response header from upstream, client: xxx.xxx.xxx.xx, server: mydomain.com, request: "POST /wp-cron.php?doing_wp_cron=1455734531.184815883245236364746093750 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fcgi-mydomain-php-fcgi-0.sock:", host: "mydomain.com"

**Comment by ruben-** [comment]
Fixed in child; https://github.com/mainwp/mainwp-child/commit/dbef577add59b3db3c2c9ba8106e324f9fe35408
