### ISSUE TITLE
Spelling and grammar issues during the initial setup of MainWP

### ISSUE THREAD

**Issue by maxwelljordanwhite** [mainwp/mainwp#350]
**Describe the bug**
2 typos during the initial setup of MainWP.

It might also make sense to have the copy include an "a" before "Unique Security ID"

**To Reproduce**

1. Install the MainWP plugin
2. Choose to run the quickstart
3. Add a site and you should see the typos (see the screenshot below)

**Expected behavior**
To be typo free :)

**Screenshots**
![4USLUTGUKl1LUxQub1hPPq9vYsaIwYkHXm7eHhNk](https://user-images.githubusercontent.com/7244793/85202286-4ee9a500-b2d3-11ea-985c-11f35f30a825.jpeg)

**Desktop (please complete the following information):**
NA

**Smartphone (please complete the following information):**
NA

**Additional context**
 Does not seem to be present when adding new sites from the MainWP dashboard.

**Comment by nkukard** [comment]
There is also a spelling mistake in README.md. "list of MainWP Exteperts" should be "list of MainWP Experts".

**Comment by bogdan-mainwp** [comment]
Thanks for the report and the pull request. Fix will be included in the next release
