### ISSUE TITLE
Sites not always adding

### ISSUE THREAD

**Issue by dsgnr** [mainwp/mainwp#37]
Hello, I am new to using MainWP. It does seem great so far. However, I am having a small issue where sites say they are added to my Parent install, but they never do. This means I have to deactivate the child plugin installation and reactivate it to get a new code.

I have checked the server information in the plugin tabs and everything is a 'pass' in there so not sure what could cause this.

Interested to hear your thoughts on how I can debug this!

Thanks,
Dan

**Comment by bogdan-mainwp** [comment]
Hi Dan,

Thanks for reaching us. Can you please open a helpdesk ticket so we can help you?
https://mainwp.com/support/

Thanks

**Comment by dennisdornon** [comment]
@dsgnr Did you submit a ticket and was your issue resolved?
