### ISSUE TITLE
Stalled upload causing duplicate backup files on remote destination

### ISSUE THREAD

**Issue by PascalAnimateur** [mainwp/mainwp#39]
I'm having problems with big backup files (<2Gb) being uploaded multiple times to a remote Dropbox destination (I'm using mainwp-remote-backup-extension). It seems the 'stalled' upload status is handled by mainwp itself by restarting the upload task.

See my other [issue](https://github.com/khromov/mainwp-remote-backup-extension/issues/1) on the forked plugin repo.

**Comment by bogdan-mainwp** [comment]
Apologies that you are experiencing an issue with the default MainWP backups.  Have you considered trying the [free Backup Extensions](https://mainwp.com/mainwp-extensions/extension-category/backup/) to see if one of them solves your problem and works better for you? 
 
We are actively moving away from the default MainWP Backups, as noted in [this blog post](https://mainwp.com/mainwp-begins-integrating-the-most-popular-backup-plugins/), so the best long term solution would be one of the Backup Extensions.
