### ISSUE TITLE
site favicon

### ISSUE THREAD

**Issue by m-e-h** [mainwp/mainwp#40]
I'm not seeing any favicons for my child sites. It looks like it's trying to use `{$childdomain}/favicon.ico`
I'm pretty sure I don't have a favicon.ico for my sites. 

If not already doing so, perhaps first check for the `site-icon` using some of the WP functions.
`has_site_icon()`
`get_site_icon_url()`

**Comment by bogdan-mainwp** [comment]
Thanks for reporting this issue and for the suggestion. I will forward this to our Dev team and have them recheck the code.

**Comment by ruben-** [comment]
Fixed in child, will be included in next release.
