### ISSUE TITLE
mainwp_cronupdatescheck_action not running with cron/updatescheck.php

### ISSUE THREAD

**Issue by Progressed36** [mainwp/mainwp#413]
**Describe the bug**
after update from the 14th the check updates on childs do not run any more. Im running a cronjob every 15 minutes
(/wp-content/plugins/mainwp/cron/updatescheck.php). last known run is the 17th because i manually checked. Running the URL manually isnt doing anything.

Check for available updates | mainwp_cronupdatescheck_action | Once every minute | September 17, 2020 06:11 | September 21, 2020 18:03
Check for new statistics | mainwp_cronstats_action | Once hourly | September 21, 2020 17:47 | September 21, 2020 18:40
Check for vulnerabilities | mainwp_cron_vulner_recheck | Once hourly | September 19, 2020 18:00 | September 21, 2020 18:59
Ping childs sites | mainwp_cronpingchilds_action | Once daily | September 21, 2020 17:48 | September 22, 2020 14:40
Send Sucuri scan notifications | mainwp_sucuri_extension_cronsecurityscan_notification | Once daily | September 20, 2020 22:14 | September 21, 2020 22:14

as you can see some things do run, but unfortunatly not the updates check. The error log has this:

AH01071: Got error 'PHP message: mainwp-activated-check is deprecated since version 4.1! Use mainwp_activated_check instead.PHP message: mainwp-extension-enabled-check is deprecated since version 4.1! Use mainwp_extension_enabled_check instead.', referer: https://manage.mundofy.com/wp-admin/admin.php?page=ServerInformationCron

**Comment by bogdan-mainwp** [comment]
Hi @Progressed36, can you please tell me do you have the MainWP Favorites Extension active on your MainWP Dashboard?

**Comment by Progressed36** [comment]
No i have not.

- Rocket Version 4.0.1 
- Advanced Uptime Monitor Version 5.0.2.1
- Client Reports Version 4.0.5.1
- Code Snippets Version 4.0.1
- Sucuri Version 4.0.8.1
- Vulnerability Checker Version 4.0.3.1

**Comment by bogdan-mainwp** [comment]
Hi @Progressed36, this issue should be resolved in the upcoming version. We are working on the Dashboard 4.1.2 version that should be out pretty soon. Let us know how it goes after you update your setup and retest the reported issue.

Thanks

**Comment by bogdan-mainwp** [comment]
Hi @Progressed36, can you please verify if the version 4.1.2 that was released yesterday solves the problem?

**Comment by Progressed36** [comment]
I ran /wp-content/plugins/mainwp/cron/updatescheck.php and it indeed updated the last runtime of the script.

However, it did not detect updates and with 45 connected sites i think its not correct finding new updates. I will wait for the cron to run this night and i will keep you posted tommorow.

**Comment by Progressed36** [comment]
like i said. it updates the runtime but doesnt actually find new updates

**Comment by Progressed36** [comment]
Last update did work 

MainWP Dashboard Version | 4.1.2.1

Ony thing left to fix is the daily digest. Every time it finds a new update it will send an email (to my spam even though im using authenticated email).

With a total score of 12 out of allowed 6 these are the biggest factors and rules it hits.

HACKED_WP_PHISHING (4.5)
BAYES_SPAM (5.1)

so its bassically the content thats triggering this.

**Comment by Progressed36** [comment]
Also, i see that its not showing every update. strangely enough i have some translation and plugin updates on  some sites and they dont come up. So finding updates seem randomly...

**Comment by bogdan-mainwp** [comment]
The problem has been fixed and it will be released in the version 4.1.3
