### ISSUE TITLE
cron/bootsrap.php will return "Unsupported WordPress setup" when ABSPATH is not defined explicitly in wp-config.php

### ISSUE THREAD

**Issue by ptrckvzn** [mainwp/mainwp#43]
I am using [Roots.io's Bedrock](https://roots.io/bedrock/docs/folder-structure/) folder structure for my WordPress sites.

```
config
  application.php
  environments
    development.php
    staging.php
    production.php
web
  app
      plugins
      themes
      uploads
  wp-config.php
  index.php
  wp
```

The [wp-config.php](https://github.com/roots/bedrock/blob/master/web/wp-config.php) located in the web root folder requires other configuration files in ../config/*. mainwp/cron/bootstrap.php is looking for the ABSPATH define statement explicitly in wp-config.php. With this setup, ABSPATH is defined in [application.php](https://github.com/roots/bedrock/blob/master/config/application.php#L82).

I wonder if it would be interesting for MainWP to support this kind of setup. For example, why not `require_once(__DIR__.'/../../../../wp-config.php');` in `cron/bootstrap.php`instead of parsing the file for ABSPATH? This would support different `wp-config.php` setup.

**Comment by ruben-** [comment]
We try to do this by first trying to use the wp-load file. If this does not succeed we manually parse the wp-config, since including it would cause errors since the wp-load takes care of loading the wordpress functions.
