### ISSUE TITLE
Chrome 'Parser-blocking, cross-origin script' warning

### ISSUE THREAD

**Issue by edflips** [mainwp/mainwp#44]
It looks like Google are are pushing ahead with blocking scripts injected with document.write, and I'm seeing warnings in the Chrome (current stable) console when enabling the mainWP Dashboard plugin.

`A Parser-blocking, cross-origin script, https://www.google.com/uds/?file=visualization&v=1&packages=corechart, is invoked via document.write. This may be blocked by the browser if the device has poor network connectivity.`

`A Parser-blocking, cross-origin script, https://www.google.com/uds/api/visualization/1.0/b5ac9efed10eef460d14e653d05f5fbf/format+en_GB,default+en_GB,ui+en_GB,corechart+en_GB.I.js, is invoked via document.write. This may be blocked by the browser if the device has poor network connectivity.`

It looks like those scripts just need to be loaded async.

**Comment by bogdan-mainwp** [comment]
Apologies for the delay. 

If the issue still persists, please [open a helpdesk ticket](https://mainwp.com/support/) so our dev team can review this.

**Comment by bogdan-mainwp** [comment]
Scheduled for the next release.

**Comment by bogdan-mainwp** [comment]
This issue is actually the MainWP Matomo Extension related. I am closing the issue here and opening internal ticket for the dev team.
