### ISSUE TITLE
No alter tables for new columns

### ISSUE THREAD

**Issue by ramonfincken** [mainwp/mainwp#453]
**The bug**
Starting may 2020 you have added some new columns to the mainwp_wp table (git version of class/class-mainwp-install.php )
Currently we are at the latest code version but are missing those colums. 

** Error log (censored) **
Got error 'PHP message: WordPress database error Unknown column 'disable_status_check' in 'field list' for query UPDATE sp_mainwp_wp SET url="https://censored.nl/", name="censored.nl", adminname="censored",pluginDir="",maximumFileDescriptorsOverride = 0,maximumFileDescriptorsAuto= 0,maximumFileDescriptors = 150, verify_certificate="0", ssl_version="0", wpe="0", uniqueId="censored", http_user="", http_pass="", disable_status_check="0", status_check_interval="0", disable_health_check="0", health_threshold="0" WHERE id=45 made by do_action('mainwp_page_managesites'), WP_Hook->do_action, WP_Hook->apply_filters, MainWP\\Dashboard\\MainWP_Manage_Sites::render_manage_sites, MainWP\\Dashboard\\MainWP_Manage_Sites::update_site_handle, MainWP\\Dashboard\\MainWP_DB->update_website', referer: https://site.ext/wp/wp-admin/admin.php?page=managesites&id=45

**Additional context**
We are missing ALTER TABLE statements for (warning: this list is generated manually by looking at the diffs, it might not be up to date).

statsUpdate
backup_before_upgrade
health_issues_total and /or health_issues
disable_status_check
disable_health_check
status_check_interval
health_threshold
health_value
http_code_noticed

**Comment by ramonfincken** [comment]
Our query: show columns from sp_mainwp_wp

result:
`




id | int(11) | NO | PRI |   | auto_increment

userid | int(11) | NO | MUL |   |  

adminname | text | NO |   |   |  

name | text | NO |   |   |  

url | text | NO |   |   |  

pubkey | text | NO |   |   |  

privkey | text | NO |   |   |  

nossl | tinyint(1) | NO |   |   |  

nosslkey | text | NO |   |   |  

siteurl | text | NO |   |   |  

ga_id | text | NO |   |   |  

gas_id | int(11) | NO |   |   |  

offline_checks_last | int(11) | NO |   |   |  

offline_check_result | int(11) | NO |   |   |  

http_response_code | int(11) | NO |   | 0 |  

note | text | NO |   |   |  

note_lastupdate | int(11) | NO |   | 0 |  

statsUpdate | int(11) | NO |   |   |  

directories | longtext | NO |   |   |  

plugin_upgrades | longtext | NO |   |   |  

theme_upgrades | longtext | NO |   |   |  

translation_upgrades | longtext | NO |   |   |  

premium_upgrades | longtext | NO |   |   |  

securityIssues | longtext | NO |   |   |  

themes | longtext | NO |   |   |  

ignored_themes | longtext | NO |   |   |  

plugins | longtext | NO |   |   |  

ignored_plugins | longtext | NO |   |   |  

pages | longtext | NO |   |   |  

users | longtext | NO |   |   |  

categories | longtext | NO |   |   |  

pluginDir | text | NO |   |   |  

automatic_update | tinyint(1) | NO |   |   |  

backup_before_upgrade | tinyint(1) | NO |   | 2 |  

backups | text | NO |   |   |  

mainwpdir | int(11) | NO |   |   |  

loadFilesBeforeZip | tinyint(1) | NO |   | 1 |  

is_ignoreCoreUpdates | tinyint(1) | NO |   | 0 |  

is_ignorePluginUpdates | tinyint(1) | NO |   | 0 |  

is_ignoreThemeUpdates | tinyint(1) | NO |   | 0 |  

verify_certificate | tinyint(1) | NO |   | 1 |  

ssl_version | tinyint(1) | NO |   | 0 |  

ip | text | NO |   |   |  

uniqueId | text | NO |   |   |  

maximumFileDescriptorsOverride | tinyint(1) | NO |   | 0 |  

maximumFileDescriptorsAuto | tinyint(1) | NO |   | 1 |  

maximumFileDescriptors | int(11) | NO |   | 150 |  

http_user | text | NO |   |   |  

http_pass | text | NO |   |   |  

force_use_ipv4 | tinyint(1) | NO |   | 0 |  

wpe | tinyint(1) | NO |   |   |  

is_staging | tinyint(1) | NO |   | 0

`

**Comment by bogdan-mainwp** [comment]
Hi @ramonfincken, thanks for reachig out and reporting this problem.
I will have our dev team check this as soon as possible.

**Comment by bogdan-mainwp** [comment]
The problem has been fixed and it will be released in the version 4.1.3

**Comment by ramonfincken** [comment]
Excellent, may I see the commits?

**Comment by bogdan-mainwp** [comment]
Hi @ramonfincken,

My apologies for the small delay here.

The dev team verified that this problem was fixed by increasing the database version number, so there is no specific commit that we can tie to it.
