### ISSUE TITLE
"Server information -> wp-config file" page is empty

### ISSUE THREAD

**Issue by Sonicelo** [mainwp/mainwp#46]
I am using non-standard wordpress instalation, where the wordpress sources are located in a subfolder.

To display the wp-config values, you are looking only directly in wordpress core folder, but Wordpress also supports having wp-config file one folder above, as we can see in the source:
https://core.trac.wordpress.org/browser/trunk/src/wp-load.php#L34

Same problem arrises, when viewing child site wp-config source file.

Error I get, as the file exist in one folder higher:

```
show_source(): Failed opening '/var/www/public_html/wp/wp-config.php' for highlighting
```

**Comment by dennisdornon** [comment]
We moved away from creating backups directly through the MainWP plugin and I would recommend one of the free [Backup Extensions](https://mainwp.com/mainwp-extensions/extension-category/backup/) that may provide the functionality you need and be more useful for you. 

We will not be making any changes to the default backups and only continuing to maintain current functionality for legacy users, you can learn more about that in [this blog post](https://mainwp.com/mainwp-begins-integrating-the-most-popular-backup-plugins/).

**Comment by Sonicelo** [comment]
It seems you simply duplicated the response from the other thread I created, I am tackling here a different issue, only setup is similar.

**Comment by dennisdornon** [comment]
You are correct, my apologies.
