### ISSUE TITLE
Add more summarizing endpoints

### ISSUE THREAD

**Issue by Bitsky** [mainwp/mainwp#463]
**Is your feature request related to a problem? Please describe.**
Several endpoints are only available for individual sites, like Site HTTP Status, Site Health Score, Site Security Issues. It would be quite an improvment for performance if there would be a single API request to get the HTTP status codes for all sites, or health scores instead of looping over all available sites.

**Describe the solution you'd like**
Endpoints like "Sites HTTP Status", "Sites Health Scores", "Sites Security Issues".

**Additional context**
I'm aware of "Sync Sites" and "Check Sites", but these don't return meaningful data.

**Comment by bogdan-mainwp** [comment]
Hi @Bitsky,

thanks for submitting your suggestion. 

Our dev team will check this asap.

Thanks

**Comment by bogdan-mainwp** [comment]
Added to version 4.1.6
