### ISSUE TITLE
New post deleted/disappeared after failing to post to child site.

### ISSUE THREAD

**Issue by nativeit** [mainwp/mainwp#466]
**Describe the bug**
I created a new post for one of my child sites. The site appears healthy in the dashboard, and other operations such as updating plugins work without issue. When I selected the site for the new post, it successfully listed the existing categories, so I am positive that the child plugin is installed and operational otherwise. After hitting "Publish", I received an error that the child plugin was not installed and the post could not be published. That in and of itself would not have been something I would create a bug report for, but the main issue is that the post itself did not save or persist in MainWP, so all of my work in composing the post has been lost. This is the first time I have tried creating a post from within MainWP, so moving forward I will compose posts in Drafts and copy the content so it isn't solely dependent on MainWP. But it seems like after an error the post should persist in MainWP as a draft, or the user should be returned to the New Post editing screen.

**To Reproduce**
1. Go to Posts
2. Click on 'Add New'
3. Compose post
4. Select site
5. Publish
6. Error states that the post could not be published because the child site plugin is not installed (even though it was).
7. Browser redirects back to the default Manage Posts screen, the original post is not listed and doesn't seem to be available anywhere.

**Expected behavior**
After an error in publishing, the post content should remain in the New Post editing interface or as a draft in Manage Posts.

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur (arm64)
 - Browser Chrome
 - Version 87.0.4280.141 (Official Build) (arm64)

**MainWP Server**
Debian Linux 9
Apache 2.4.25
PHP 7.4
Wordpress 5.6
MainWP v4.1.2.1
MainWP BackWPup v4.0.2.1
(No other plugins installed)

**Child Site**
Hosted on same server as MainWP
PHP 7.0.33
Wordpress 5.5.3
MainWP Child 4.1.3.1
(Several other plugins installed, list of plugins available on request)
Last check status 200-OK
Synchronized successfully as of the time of this report

**Additional context**
I would post the specific error message here, but test posts that I have since made to try and reproduce the error have all posted successfully.

Thanks to the devs for all of their hard work in creating and maintaining MainWP. I will troubleshoot the connection issue with the site myself, I just wanted to address the core issue of losing the post content following the error.

**Comment by bogdan-mainwp** [comment]
Hi @nativeit,

thanks for reaching out and my apologies for the delay in here. This is not our official support channel so reports can be missed easily.

I tried to duplicate this problem, but I couldn't. 

Can you please check if you can duplicate this behavior with the latest MainWP plugin version and if yes, please feel ree to open a [helpdesk ticket](https://mainwp.com/my-account/get-support/) so we can check this further?

Thanks!
