### ISSUE TITLE
Basic Uptime Monitoring Email does not work until Email Notification settings are saved first time

### ISSUE THREAD

**Issue by dtugend** [mainwp/mainwp#477]
The mainwp_settings_notification_emails option is only created when the email settings are saved the first time.

The problem is that in the UI they are enabled by default, but the defaults are disabled then in [get_general_email_settings](https://github.com/mainwp/mainwp/blob/94644ea6095eb6b65f49cdc1a267beabae0343db/class/class-mainwp-notification-settings.php#L387)

**Comment by dtugend** [comment]
I now found the actual issue and edited the issue accordingly. (My guess earlier was wrong, sorry.)

**Comment by bogdan-mainwp** [comment]
Hi @dtugend,

thanks for reaching out and reporting this. 
I will have our dev team check this.

**Comment by dtugend** [comment]
I don't want to waste your time, somehow it's still not sending the email, I don't know why, but I am still wrong, so closing until I found it for real, sorry.

**Comment by dtugend** [comment]
I had the right idea: the problem is email_settings recipient is empty (which is used), until the settings are saved the first time.
So it sends to no one, unless sites have individual emails setup ($admin_email is not used, because it's called with default false):https://github.com/mainwp/mainwp/blob/94644ea6095eb6b65f49cdc1a267beabae0343db/class/class-mainwp-monitoring-handler.php#L270

**Comment by bogdan-mainwp** [comment]
Fixed in 4.1.6
