### ISSUE TITLE
Sites Monitoring: Individual intervals lower than global interval are not honored

### ISSUE THREAD

**Issue by dtugend** [mainwp/mainwp#478]
**Describe the bug**
The documentation (https://kb.mainwp.com/docs/sites-monitoring/) says:
> It is possible to set different checking intervals for each child individually, Site Health threshold, or even disable monitoring. 

However the actual implementation of the cron job cancels runs out according to the global setting:
https://github.com/mainwp/mainwp/blob/003e4a99b3775d7e23a1b7413f476bfa51975bf0/class/class-mainwp-system-cron-jobs.php#L1484

This means setting individual sites to a lower setting will not work as intended, they will still not run more often that the global setting.

**To Reproduce**
1. Set global to e.g. 1 hour.
2. Set an individual site to 10 minutes.
3. Observe that the site is still only checked once an hour.

**Expected behavior**
Preferably it could be fixed in the implementation, otherwise the documentation should be clear about this, please.

**Comment by bogdan-mainwp** [comment]
Hi @dtugend,

Thanks for reporting this. Our dev team will check this.

**Comment by bogdan-mainwp** [comment]
Problem has been resolved and the fix is scheduled for version 4.2.1
