### ISSUE TITLE
Bug in MainWP "Basic Security Check" destroys DIVI Builder

### ISSUE THREAD

**Issue by sunezapa** [mainwp/mainwp#479]
In Basic Security/Check for a website using Divi Theme (or just Divi Builder I assume),
the Divi editing funtionality is destroyed if the isssue "**Scripts and Stylesheets version information has been removed from URLs**" are fixed in MainWP.

My investigating (all plugins disable/enable etc) show that this single Fix do the catastrophe,
and is confirmed by FIXing and UNFIXing, to be sure, that it IS this setting that to the problem.

In Divi builder, with the FIX of this setting, the whole body of the edited page is hidden, leaving only hte header and footer visible, whenever any mouseover divi-controil are clicked. For Example mouseover the green control and clicking either settings ikon or add row icon do collapse of the body. Or clicking the black + for Add Module.

1. Here is what should happen by clicking black + Add Module: https://www.screencast.com/t/BSn0Uygrss 

2. Now I go to MainWp and click FIX for the issue: https://www.screencast.com/t/O1vGQvjt

3. The result, collapsed body, when repeating step 1: https://www.screencast.com/t/TgDKYSG8lQ6j

I leave that setting UNFIXED ;-)
I PROPOSE an option for marking an issue as "HIDE" or similar, so MainWP do not show "there is an issue" on front page, which is annoying, and disturbing from identifying other issues with security.

Of course no. 1 is a solution where this FIX not anymore will inferfere negatively with Divi Builder...

**Comment by bogdan-mainwp** [comment]
Hi @sunezapa,

In version 4.1.6, we have removed the mentioned security check/fix so it should not cause issues any longer.

Thanks

**Comment by sunezapa** [comment]
Hello Bogdan,
thanks, nice, almost fixed,
I see it is partially fixed, BUT:

The dashboard still mention (actual) 3 issues
     [image: image.png]
even the 4.1.6 version did remove the actual fix.

Similar, if I click DETAILS for a website, I see only green checks,
but the dashboard - and the "details" still shows "3 issues" (same issue
for the 3 websites using Divi),
and the website status also has the FIX ALL button active, even all the
checks are green.

(I did not dare to click "Fix all" for the risk of still fixing, and no
"Undo" option).

 [image: image.png]
 [image: image.png]

Den tir. 20. apr. 2021 kl. 19.24 skrev Bogdan Rapaić <
***@***.***>:
