### ISSUE TITLE
File backup only includes folders inside Wordpress directory

### ISSUE THREAD

**Issue by Sonicelo** [mainwp/mainwp#49]
Similar to #46 I have a custom folder configuration and I noticed, that your data backup only includes files inside WordPress directory. If you could include the folders defined by WP_CONTENT_DIR, WP_PLUGIN_DIR, UPLOADS by your backup-er. Currently your database backup service is useless to me because of this.

**Comment by dennisdornon** [comment]
We moved away from creating backups directly through the MainWP plugin and I would recommend one of the free [Backup Extensions](https://mainwp.com/mainwp-extensions/extension-category/backup/) that may provide the functionality you need and be more useful for you. 

We will not be making any changes to the default backups and only continuing to maintain current functionality for legacy users, you can learn more about that in [this blog post](https://mainwp.com/mainwp-begins-integrating-the-most-popular-backup-plugins/).
