### ISSUE TITLE
Filter mainwp_sitestable_item does not include the name of the column being displayed

### ISSUE THREAD

**Issue by contactashish13** [mainwp/mainwp#490]
**Describe the bug**
The example given [here](https://mainwp.dev/hooks/mainwp_sitestable_getcolumns/) adds only 1 column. If I want to add 2 columns I am not aware of which column I'm currently processing because the `$item` parameter in the filter `mainwp_sitestable_item` does not contain the name of the column that was added using the filter `mainwp_sitestable_getcolumns`.

**To Reproduce**
Steps to reproduce the behavior, use the below code
```
add_filter( 'mainwp_sitestable_getcolumns', 'mycustom_sites_table_column', 10 );
add_filter( 'mainwp_sitestable_item', 'mycustom_sitestable_item', 10 );

function mycustom_sites_table_column( $cols ) {
   $cols['wpversion'] = 'WP Version';
   $cols['wpversion-clone'] = 'WP Version Clone';
   return $cols;
}

function mycustom_sitestable_item( $item ) {
   // how do I know whether I'm showing data for 'wpversion' or 'wpversion-clone'
   return $item;
}
```

**Expected behavior**
While displaying the results in multiple custom columns, we should know which column we are processing.

**Desktop (please complete the following information):**
 - OS: Any
 - Browser Any
 - Version 4.1.6

**Smartphone (please complete the following information):**
 - Device: Any
 - OS: Any
 - Browser Any
 - Version 4.1.6

**Additional context**
The filter can send the second parameter as the `$column_name` viz. [this line](https://github.com/mainwp/mainwp/blob/master/class/class-mainwp-manage-sites-list-table.php#L185) should change to 

```
$item = apply_filters( 'mainwp_sitestable_item', $item, $column_name );
```

**Comment by bogdan-mainwp** [comment]
Hi @contactashish13,

thanks for pointing out this problem. It's now fixed in commit [f85afc9](https://github.com/mainwp/mainwp/commit/f85afc90394a3bc01e9197d273187e44bc8d29ee)
