### ISSUE TITLE
BUG: TLS Issues with TLS Dashboard and non-TLS Child Sites

### ISSUE THREAD

**Issue by benyanke** [mainwp/mainwp#50]
When the dashboard is loaded over TLS, and the child site does not support TLS, the favicon loading in the dashboard breaks the TLS connection, because it loads directly from the child's server.

I suggest proxying the favicons through the dashboard install, so that they can all be loaded securely.

**Comment by bogdan-mainwp** [comment]
Thanks for reporting this issue. 
Would you be able to open a [helpdesk ticket](https://mainwp.com/support/) so I can have our dev team on this?

**Comment by benyanke** [comment]
Submitted.

**Comment by bogdan-mainwp** [comment]
Thanks

**Comment by bogdan-mainwp** [comment]
Issue fixed in one of the previous versions.
