### ISSUE TITLE
FEATURE SUGGESTION: Redirection To Dashboard

### ISSUE THREAD

**Issue by benyanke** [mainwp/mainwp#51]
I would suggest allowing automatic frontend-blocking/redirection-to-backend as a feature.

At least with my configuration, this simple htaccess rule allows this.

```
# Redirect all frontend requests to backend
RewriteCond %{REQUEST_URI} !/wp-.* [NC]
RewriteRule ^(.*)$ /wp-admin/admin.php?page=mainwp_tab [L,R=302]
```

If users are, as you suggest, setting up dedicated wordpress installs to function as dashboards, this would be a desirable feature to add for easy implementation without editing the htaccess file manually. Of course, the destination URL could be modified as desired.

**Comment by bogdan-mainwp** [comment]
Thanks for submitting your idea. Please check the [MainWP Clean & Lock Extension](http://mainwp.com/extension/clean-and-lock/), I believe that it would allow you to do something very similar.
