### ISSUE TITLE
Can't find a way to enable gutenberg block editor

### ISSUE THREAD

**Issue by LukaszJaro** [mainwp/mainwp#518]
Hi,

Using this plugin for the first time, looks very impressive. I just was wondering why the classic editor is still being used? This doesn't align well with my sites we are using the block editor.

In fact the mainwp site seems to encourage classic editor usage?

**Comment by bogdan-mainwp** [comment]
Hi @LukaszJaro,

At the moment, MainWP supports only the Classic Editor.

**Comment by LukaszJaro** [comment]
Thanks, that is very unfortunate!
