### ISSUE TITLE
Add new site on SSL not always working

### ISSUE THREAD

**Issue by milsorm** [mainwp/mainwp#53]
Hi folks,

when I try to add my SSL-enabled sites and properly choose in Add Single Site dialog "https" instead of "http" in select box, I received times to times (and more frequently these days) error that MainWP Child cannot be detected.

After several hours of investigation I found that this "https" information is ignored in deep of function calls and in `fetchUrl` function is called `curl` on http scheme. Because I have 301 redirects from http to https, curl will redirect to https, but unfortunately with debug information:

```
  * Violate RFC 2616/10.3.2 and switch from POST to GET
```

I can solve this via workaround:

```
  @curl_setopt( $ch, CURLOPT_POSTREDIR, 3 );
```

but this is only workaround, not correct solution.

Can you please investigate why http scheme is used instead of proper https? Or at least add this `curl_setopt` to main branch?

Thanks a lot
Milan

**Comment by bogdan-mainwp** [comment]
Hi Milan,

Have you been able to duplicate this issue again after our last release ( Jan 5th, 2017 )?

Thanks

**Comment by milsorm** [comment]
I’ve changed after upgrade curl configuration again :(

But I will made some tests in new release during next weekend.

**Comment by milsorm** [comment]
It is the same behaviour also in new version. And of course the thing in Reconnect. So I add that call to every curl call inside utility class and after that MainWP works normally.

**Comment by milsorm** [comment]
Resubmit to MainWP ticket.

**Comment by bogdan-mainwp** [comment]
milsorm, if the issue still persists, please feel free to reopen the ticket in your MainWP account, for now, I will go ahead and mark this issue as closed.
