### ISSUE TITLE
Github login on MainWP Community broken

### ISSUE THREAD

**Issue by FeIix** [mainwp/mainwp#543]
Hi,
It seems that the "Login with Github" button on the MainWP Community website isn't working since today,

I have this error : "Sorry, there was an error authorizing your account. Please try again."

**Comment by bogdan-mainwp** [comment]
Hi Felix,

it could be that the problem is caused by switching meta.mainwp.com to managers.mainwp.com 

Can you please try a different browser and clear all cache and try again?

**Comment by bogdan-mainwp** [comment]
Ok, verified that there was a problem in settings and now it's fixed.

**Comment by FeIix** [comment]
I confirm it's working again  👍
