### ISSUE TITLE
admin.php?page=mainwp_about&do=whatnew: multisite main site wp-admin redirect loop after mainwp update

### ISSUE THREAD

**Issue by lkraav** [mainwp/mainwp#55]
I'm fairly certain this started in the last few months. Wouldn't be surprised if object caching issue again, like #26.

**Comment by lkraav** [comment]
Commenting out this conditional block helped https://github.com/mainwp/mainwp/blob/master/class/class-mainwp-system.php#L1898

I would really appreciate if you wouldn't mess with people admins with forced redirects.

**Comment by bogdan-mainwp** [comment]
The issue has been fixed in one of the previous versions. 

I will go ahead and close this issue.
