### ISSUE TITLE
Undefined index in CLI when calling site info

### ISSUE THREAD

**Issue by maximejobin** [mainwp/mainwp#557]
When you request info using CLI, you get this if the site's data does not exist:
![image](https://user-images.githubusercontent.com/1080760/171654090-477c83e5-510b-4ed4-bbc3-2b0654f9a270.png)

From this function:
https://github.com/mainwp/mainwp/blob/master/class/class-mainwp-wp-cli-handle.php#L467

To fix, there should be an `if` to check if variables are defined before displaying them.

**Comment by bogdan-mainwp** [comment]
Hi @maximejobin,

thanks for reaching out and reporting this.
Our dev team fixed this problem and the fix will be included in the version 4.2.6.
