### ISSUE TITLE
cannot ignore plugin updates through the plugins menu

### ISSUE THREAD

**Issue by bfcmaintenance** [mainwp/mainwp#576]
i get different behavior when i ignore a plugin via these two methods: 

### working
`Updates > [click a plugin] > Ignore Update (not ignore globally)`
<img width="548" alt="Screen Shot 2022-09-29 at 8 52 52 PM" src="https://user-images.githubusercontent.com/84864181/193167593-02700022-0e5c-4823-ae9b-55690f475be3.png">

this succeeds in ignoring the update (though [not in the cli](https://github.com/mainwp/mainwp/issues/575)). In `Plugins > Ignored Updates > Per Site Ignored Plugins`: 

Site | Plugin | Plugin slug
-- | -- | --
-- | GravityForms | gravityforms/gravityforms.php

### not working
Plugins > Manage Plugins > [select a plugin] > Bulk Actions > Ignore updates > Apply

this does not work.
 In `Plugins > Ignored Updates > Per Site Ignored Plugins`: 

Site | Plugin | Plugin slug
-- | -- | --
-- | Gravity Forms | gravityforms%2Fgravityforms.php

**Comment by bogdan-mainwp** [comment]
Hi @bfcmaintenance, 

I just tried to duplicate the problem, but I couldn't.
Can you please check if any of resent updates resolved this problem for you and if you still experience the issue, please open a [helpdesk ticket](https://mainwp.com/my-account/get-support/) so our support team can assist.

Thanks
