### ISSUE TITLE
Add an option to force use of IPv4

### ISSUE THREAD

**Issue by pjjackowski** [mainwp/mainwp#58]
After successfully having added a handful of sites to my dedicated MainWP installation (WP 4.7.3, MainWP 3.3.1), I was unable to add another one. I had a closer look and found out this "uncooperative" one had IPv6 address that was different than IPv6 address of those sites I was able to add; they all share the same IPv4 address, though. After forcing IP4 check by adding these lines:

>    if (defined('CURLOPT_IPRESOLVE') AND defined('CURL_IPRESOLVE_V4')) {`
>        curl_setopt($ch, CURLOPT_IPRESOLVE, CURL_IPRESOLVE_V4);
>    }

to `tryVisit()` in `class-mainwp-utility.php` I was able get 200 response in Test Connection (instead of 405), and when I've added them to `_fetchUrl()` I was able to actually add a site to my MainWP dashboard; adding them to `fetchUrlsAuthed()` enabled remote plugin installation etc.

Now, obviously, new version would overwrite my changes, so could you please help make them permanent and add an option to force IP4 check somewhere in the settings? I guess I'm not the only who would benefit by this enhancement ;-)

**Comment by bogdan-mainwp** [comment]
This issue is being reviewed by the Dev team.

**Comment by bogdan-mainwp** [comment]
Included in version 3.4.3
