### ISSUE TITLE
WP-CLI - Ignored plugin updates notices

### ISSUE THREAD

**Issue by maximejobin** [mainwp/mainwp#596]
Running the following CLI command:

    wp mainwp updates --ignored-plugins-updates

... outputs the following notices.

    Notice: Undefined variable: website in /home/xxxxxxx/mainwp/wp-content/plugins/mainwp/class/class-mainwp-wp-cli-handle.php on line 1499
    Notice: Trying to get property 'name' of non-object in /home/mainwp/xxxxxxx/wp-content/plugins/mainwp/class/class-mainwp-wp-cli-handle.php on line 1499

**Expected behavior**
No notice, warning or error messages.

**Comment by maximejobin** [comment]
This issue is not linked with what I wrote on Meta. On Meta, it was a question. Here, it is code improvements.

My bad for not telling you the version I was using but yes, it is 4.3.1.

If you check this line: https://github.com/mainwp/mainwp/blob/master/class/class-mainwp-wp-cli-handle.php#L1499

You will see that this issue should not be closed. It should be fixed. The `$website` variable is used but was never initialized.

**Comment by kwcjr** [comment]
I have tested the following MainWP CLI Commends:
`wp mainwp updates --ignored-plugins-updates`
`wp mainwp updates --ignored-plugins-updates 1`

No errors have been returned as stated in your original post... 

---

The variable in question "$website" has a default value of "false" defined via the function parameters as per the PHP documentation here: https://www.php.net/manual/en/functions.arguments.php#functions.arguments.default

`public static function callback_updates_site_ignored_plugins_updates( $args = array(), $assoc_args = array(), $website = false ) {`

Please double check that you are using the correct version of MainWP Dashboard as well as MainWP Child Plugin.

**Comment by maximejobin** [comment]
Can you make sure you activated your debug and deactivated all other plugins?

Not initializing will ALWAYS produce some kind of error (notice, warning or fatal error) depending on the usage. This is not my opinion, it is a fact. :-)

Finally, here is the command line execution:

    $ wp core version
    6.1.1
    $ wp plugin list
    +-------------------------------------+----------+--------+---------+
    | name                                | status   | update | version |
    +-------------------------------------+----------+--------+---------+
    | advanced-uptime-monitor-extension   | active   | none   | 5.2.2   |
    | mainwp-code-snippets-extension      | active   | none   | 4.0.3   |
    | mainwp                              | active   | none   | 4.3.1   |
    | mainwp-clean-and-lock-extension     | active   | none   | 4.0.2   |
    | mainwp-domain-monitor-extension     | inactive | none   | 4.0.1   |
    | mainwp-favorites-extension          | active   | none   | 4.0.11  |
    | mainwp-google-analytics-extension   | active   | none   | 4.0.5   |
    | mainwp-lighthouse-extension         | active   | none   | 4.0.2   |
    | mainwp-pro-reports-extension        | active   | none   | 4.0.13  |
    | mainwp-team-control                 | active   | none   | 4.0.3   |
    | mainwp-branding-extension           | active   | none   | 4.1.3   |
    | mainwp-woocommerce-status-extension | active   | none   | 4.0.8   |
    | mainwp-wordfence-extension          | active   | none   | 4.0.9   |
    | seopress-for-mainwp                 | inactive | none   | 1.2.0   |
    | updraftplus                         | active   | none   | 1.22.24 |
    | wordfence                           | active   | none   | 7.8.2   |
    | wp-mail-smtp-pro                    | active   | none   | 3.7.0   |
    +-------------------------------------+----------+--------+---------+
    $ wp mainwp updates --ignored-plugins-updates

    Notice: Undefined variable: website in /home/mainwp/webapps/mainwp/wp-content/plugins/mainwp/class/class-mainwp-wp-cli-handle.php on line 1499
    Notice: Trying to get property 'name' of non-object in /home/mainwp/webapps/mainwp/wp-content/plugins/mainwp/class/class-mainwp-wp-cli-handle.php on line 1499
    Ignored Updates

    $

Of course, errors are enabled and displayed in my case on the command line.
