### ISSUE TITLE
Theme is missing styles for WordPress core UI elements

### ISSUE THREAD

**Issue by redoper1** [mainwp/mainwp#598]
**Describe the bug**
It appears that the dashboard styles don't edit the CSS of the WP core UI elements like for example notices.

**To Reproduce**
1. Trigger notice at your site with the MainWP dashboard
2. Go to your MainWP dashboard
3. See that notice will be partially hidden behind the menu as it's styled to be full-width and in case of the dark theme, it will have a white background with white text.

**Expected behavior**
WP core UI elements will be styled to match the general style of the dashboard and will be placed correctly in the layout.

**Desktop:**
 - OS: Windows 11
 - Browser: Microsoft Edge
 - Version: 109.0.1518.78

**Comment by bogdan-mainwp** [comment]
Hi @redoper1,

Thanks for reaching out.
Can you please send us a screenshot so we can see and understand the problem?
Thanks

**Comment by redoper1** [comment]
Hi @bogdan-mainwp,

yeah sure, no problem.

Here is the original
![Original](https://files.davidrychly.cz/github-files/mainwp-issue/screenshot-wp-dash.davidrychly.cz-2023.02.15-22_42_27.png)

And here is the same notice with the applied left margin and the text is highlighted, because it wouldn't be visible
![With added left-margin](https://files.davidrychly.cz/github-files/mainwp-issue//screenshot-wp-dash.davidrychly.cz-2023.02.15-22_44_26.png)

**Comment by bogdan-mainwp** [comment]
Hi @redoper1,

Tweak is in the place and it will be included in the next release.
