### ISSUE TITLE
Plugin doesn't work if site is managed sia SSH

### ISSUE THREAD

**Issue by ArjonBu** [mainwp/mainwp#60]
If I configure your site like [this](https://www.digitalocean.com/community/tutorials/how-to-configure-secure-updates-and-installations-in-wordpress-on-ubuntu), I can not install plugins or themes via mainwp dashboard on a client site.

**Comment by bogdan-mainwp** [comment]
Apologies for the delay. Can you please [open a helpdesk ticket](https://mainwp.com/support/) so our dev team can troubleshoot this issue?

**Comment by Arjoni** [comment]
I already did. They said that mainwp doesn't support accessing files if wordpress is configured to connect via ssh.

**Comment by milsorm** [comment]
You can use my solution for FTPEXT (it is very similar for SSH) in https://github.com/mainwp/mainwp/issues/68

**Comment by Arjoni** [comment]
Any update on this?

**Comment by bogdan-mainwp** [comment]
The dev team is still reviewing this issue. Please allow us more time for this.

**Comment by bogdan-mainwp** [comment]
At the moment, MainWP supports only `FTPEXT` for `FS_METHOD`. 

Feature suggestions can be submitted in the Features section of the [MainWP Community](https://meta.mainwp.com/).
