### ISSUE TITLE
text error in WordPress Updates screen

### ISSUE THREAD

**Issue by jaapwiering** [mainwp/mainwp#614]
**Describe the bug**
The text "Update All Selected" should read "Update Selected Sites"

**To Reproduce**
1. Open MainWP Dashboard
2. Behind "WordPress Updates" click on "See Details"

**Screenshots**
![IMG_6416](https://github.com/mainwp/mainwp/assets/6204903/0d744d8c-fa4a-4700-a4ac-0a0a99d57c07)

**Comment by bogdan-mainwp** [comment]
Hi @jaapwiering,

Thanks for your suggestion. We made the update an included it in the 4.4.3 release
