### ISSUE TITLE
3.4.1: moment.js conflict with Gutenberg

### ISSUE THREAD

**Issue by lkraav** [mainwp/mainwp#63]
Gutenberg fails to load with a Moment version conflict JS error, when MainWP is activated.

**Comment by bogdan-mainwp** [comment]
Are you getting this issue on the Dashboard site or child sites?

**Comment by bogdan-mainwp** [comment]
We were able to duplicate the issue and the dev team is working on this.

**Comment by bogdan-mainwp** [comment]
The dev team fixed the issue, please contact us on https://mainwp.com/support/ if you want me to send you the pre-release version.

**Comment by lkraav** [comment]
Thanks for attending. I can hold off re-activating until you release the next minor version (y).

**Comment by bogdan-mainwp** [comment]
This fix has been included in the 3.4.2 version. 

I will go ahead and mark this issue as closed.
