### ISSUE TITLE
MainWP Logo not working in README.md

### ISSUE THREAD

**Issue by FlorinBuffet** [mainwp/mainwp#633]
**Describe the bug**
The MWP-Logo is not displayed in the README.md file. The URL you link to is not available anymore.

**To Reproduce**
1. Open [README.md](https://github.com/mainwp/mainwp#readme)
2. Look at the top of the file

**Expected behavior**
Logo should be visible or just not there, but no broken link...

**Screenshots**
Not necessary

**Device (please complete the following information):**
Not relevant

**Comment by bogdan-mainwp** [comment]
Hi @FlorinBuffet, the problem is resolved.
