### ISSUE TITLE
Add a class to admin listing(s)

### ISSUE THREAD

**Issue by StaggerLeee** [mainwp/mainwp#64]
Can you please just add new class to table rows in Sites listings ?
Take name of a Group and make new class. That way we can manually with CSS change table row background depending of what Group a Site is in.

You know, what is allowed to do for localhost, quick bulk update of everything, cannot be allowed for "Live" websites.

So when it is not allways visually clear if Site is localhost or Live (by own groups say), mistakes can easy happen.

Please, just one new class. Grab Group slug and add table row classes dynamically.

**Comment by bogdan-mainwp** [comment]
Thanks for submitting this suggestion, I will talk to the dev team and have them add this in the next release.

**Comment by bogdan-mainwp** [comment]
The HTML markup of the Manage Sites table has been updated and this will be included in the next release. 

Each table row will contain the following: id="child-site-$id" and class="$groups"

**Comment by StaggerLeee** [comment]
I will close issue and thank you.
