### ISSUE TITLE
mainwp_synced_all_sites not triggering upon daily cron-sync

### ISSUE THREAD

**Issue by patrik-schoon-axelsson** [mainwp/mainwp#641]
The [mainwp_synced_all_sites](https://mainwp.dev/hooks/mainwp_synced_all_sites/) hook does not appear to trigger upon the completion of the MainWP daily synchronization. 

1) Create a function to create some form of loggable notice of the function firing and hook it to [mainwp_synced_all_sites](https://mainwp.dev/hooks/mainwp_synced_all_sites/)
2) Trigger synchronization of all child sites in the GUI. Your function triggers.
3) Await the cronjob that runs daily synchronization. Your function will not trigger or log.

**Expected behavior**
It would seem natural that this hook fires when child sites synchronize, whether intentionally or by cron, so that you could tie events that check for the status of child-sites to this event for extensions and the like.

**Additional context**

Server information:

PHP v.8.2
CloudLinux 8
Litespeed Enterprise webserver

**Comment by bogdan-mainwp** [comment]
Hi @patrik-schoon-axelsson,

thanks for reporting this. 
We checked this and fixed the problem.
We will include the fix in the next official release.

Thanks!
