### ISSUE TITLE
Update plugin from custom folder

### ISSUE THREAD

**Issue by StaggerLeee** [mainwp/mainwp#65]
I did not need this one much before. But in last time I take more and more most old and abandoned plugins from repository, Github mostly,, fork them, customize, disable update code and all update calls.

It would be useful with new feature for developers to be able to update a plugin on all websites from custom folder ?

As not so much involved in how MainWP works in deep, I believe it would be enough that MainWP check version we state in custom plugin. Each time we change code we coul just rise version number. Maybe one reset option too, when as usual there are much changes in code and it gets difficult with versioning. To start from say version 1.0 again.

I do not know how it would work really. It would need FTP permissions to directly delete, write folders and files. I guess ordinary update mechanism would not fit there. Unless we make in our forks, custom plugins, real, by all standards, update mechanism,

I use it more and more in last time. Just one last example. I needed to take over one old Valuta Converter plugin, and changed very much in code. Now it would be nice if we could update our own plugins from site to site somehow. From Localhost I mean.

**Comment by bogdan-mainwp** [comment]
For feature requests, please check this page: https://mainwp.com/mainwp-roadmaps/

However, I believe that you could use the following method to update your sites:
1. After updating plugin code, zip the plugin into a zip archive
2. Login to your MainWP Dashboard
3. Go to the MainWP > Plugins > Install > Upload page
4. Upload the plugin archive file
5. Select the wanted sites
6. Make sure that the "Overwrite Existing" option is selected
7. Complete the Installation

This process will overwrite the existing version of the plugin on the selected sites and basically, it will be updated to your latest version.

**Comment by StaggerLeee** [comment]
So simple. How could I miss than. Thank you.
