### ISSUE TITLE
Release Tag for version 5.0.2 and 5.0.3 is missing 

### ISSUE THREAD

**Issue by LvckyAPI** [mainwp/mainwp#666]
Hey @bogdan-mainwp,
Again I can't find a version Tag for the Version 5.0.2 and 5.0.3.
Can you please create a tag, so that I can update the plugin in our Docker Setup?

### or build a pipeline (I've made an action for you #667)

--- 

![image](https://github.com/mainwp/mainwp/assets/47639297/818ed639-dd2a-437b-ac22-7da98edcd144)

---

## Btw:

Packagist isn't up-to-date too
![image](https://github.com/mainwp/mainwp/assets/47639297/c40f16d6-bfeb-4682-996c-36746d495f2a)

Kind Regards

**Comment by bogdan-mainwp** [comment]
Hi, my apologies once again for being late with tags.
5.0.3 is now created so you can update.
