### ISSUE TITLE
[Feature Request] Support ftpext upgrading

### ISSUE THREAD

**Issue by milsorm** [mainwp/mainwp#68]
Hi folks,

I am using MainWP on many sites and it works perfectly, but only for `direct` `FS_METHOD` access for update and upgrade. If I want to use `FS_METHOD` `ftpext`, there is no way how to provide credentials for FTP access to MainWP Child.

I recommend to allow storing FTP credentials on MainWP server (can be encrypted in DB via some system key or whatever) and send this FTP credentials together with update request to MainWP Child.

On MainWP child you can hook request_filesystem_credentials:

```
add_action( 'request_filesystem_credentials', 'fsCredentials', 99, 7 );
```

and `fsCredentials` method (pass-through stub below)

```
function fsCredentials ( $output, $form_post, $type, $error, $context, $allow_relaxed_file_ownership, $extra_fields ) { 
  return $output; 
}
```

can detect MainWP environment (there is `mainwpsignature` and `function` in `$_REQUEST`) request and return array consisting of credentials (hostname, port, username, password, connection_type) instead of the first argument (typically empty string meaning TO OPEN credentials form).

Tested, worked, but I'm getting credentials from my local encrypted store (from remote store it will be better, especially if we combine local encryption key and MainWP Server storage).

Because a lot of WP sites sits on same server (let say farm of 15 physical servers, 30+ WP on each, mostly separated between 5-10 accounts on each), it will be better to create something like credential groups on MainWP server and store password in these groups and associate WP site to credential group.

Thanks a lot, this will helps a lot.

**Comment by bogdan-mainwp** [comment]
milsorm, thanks for the suggestion, the dev team will check this and see what they can do.

**Comment by bogdan-mainwp** [comment]
Still under review.

**Comment by Du-St** [comment]
Hello,

we are also facing this issue.

Our use case is:
- to allow site administrators to fully manage themes or plugins (install, update, delete) using "ssh" FS_METHOD (i.e. using the plugin SSH SFTP Updater Support), because FS_METHOD "direct" is not recommended by WP authors (https://wordpress.org/support/article/hardening-wordpress/ )
- to have the possibility manage sites by MainWP (in our case read-only access is sufficient)
