### ISSUE TITLE
[Feature Request] Minimum required plugins per group

### ISSUE THREAD

**Issue by milsorm** [mainwp/mainwp#69]
Hi folks,

on most WP sites I want to have some collection of plugins. Please allow to create a list of plugins required per group so if I associate WP site to group "Customer" it will automatically add request for 5-7 minimum plugins used by every customer (security). Another group "ACF" will add all my plugins around ACF, CPT UI, repeater etc.

And of course to all sites I want some minimal "default" list of plugins (Wordfence, Apocalypse, wp-bcrypt etc.) in separate list of minimum requirements.

If it will be complicated to automatically install those plugins, also comparison list "on which site there is missing / deactivated" such plugins will be great.

Thanks a lot, I will appreciate it.
Milan

**Comment by bogdan-mainwp** [comment]
Milan, thanks for the idea. However, it would be the best to follow this process: https://mainwp.com/mainwp-roadmaps/ so the idea can be submitted to feature request section properly and don't get lost.
