### ISSUE TITLE
Cost Tracker - Add renewal frequency for half year

### ISSUE THREAD

**Issue by CodeShakingSheep** [mainwp/mainwp#695]
**Is your feature request related to a problem? Please describe.**
I have a plugin subscription which renews half-yearly (every 6 months). I cannot correctly track it in the cost tracker as the available renewal frequencies are "Weekly", "Monthly", "Quarterly", "Yearly".

**Describe the solution you'd like**
I want to be able to choose a half-yearly (6 months) renewal frequency in the renewal frequency dropdown.

**Describe alternatives you've considered**
Tracking it with 1/6 of the price as monthly.

**Additional context**
Add the new frequency in this dropdown.
![image](https://github.com/mainwp/mainwp/assets/19874562/f101226b-a2b2-42b7-a2e7-f0aa2b137f04)

**Comment by bogdan-mainwp** [comment]
Hi @CodeShakingSheep, please use the https://feedback.mainwp.com/ for feature suggestions. There we can track it better and other users can upvote suggestions.
