### ISSUE TITLE
DataTables warning: Incorrect column count

### ISSUE THREAD

**Issue by CodeShakingSheep** [mainwp/mainwp#696]
**Describe the bug**
After the latest update to version 5.1 I receive the following notification:

```
DataTables warning: table id=mainwp-woocommerce-status-top-sellers-table - Incorrect column count. For more information about this error, please see https://datatables.net/tn/18
```

**To Reproduce**
Just load the overview page.

**Expected behavior**
The column count should be correct / there shouldn't be a DB error displayed.

**Screenshots**
![image](https://github.com/mainwp/mainwp/assets/19874562/10332e2e-5d5a-4ff9-b228-bf6f74e212b4)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser: Brave
 - Version: Version 1.67.116 Chromium: 126.0.6478.71 (Official Build) unknown (64-bit)

**Comment by bogdan-mainwp** [comment]
Hi @CodeShakingSheep, 

This problem comes from the WooCommerce Status extension. We released an update for this extension on June 18th. Please update the extension to the version 5.0.3 to resolve the problem.

**Comment by CodeShakingSheep** [comment]
Thanks, the update fixed it.
