### ISSUE TITLE
Upload plugin file not working

### ISSUE THREAD

**Issue by kbourro** [mainwp/mainwp#702]
**Describe the bug**
I am using Litespeed with PHP 8 and upload plugin stopped working on latest version. I downgraded to 4.6.0.1 and it works.

**To Reproduce**
1. Go to wp-admin/admin.php?page=PluginsInstall
2. Click on Upload zip file
3. Select file and error will appear

**Expected behavior**
File should be uploaded

**Screenshots**
![Screenshot 2024-09-17 151549](https://github.com/user-attachments/assets/59eaeb2c-7d96-4b3c-9279-c58d99ba862c)
![Screenshot 2024-09-17 151614](https://github.com/user-attachments/assets/7571de57-6f50-4680-86d1-7f122beee4ab)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version latest

**Comment by bogdan-mainwp** [comment]
Hi @kbourro, 

thanks for reaching out. It might be best if you could [open a helpdesk ticket](https://mainwp.com/my-account/get-support/) so our support team can help. 

Roling back to version 4.6 is not something that I would recommend, it will cause more compatibility problems.
