### ISSUE TITLE
Chunks sizes should be customisable

### ISSUE THREAD

**Issue by sixela** [mainwp/mainwp#708]
**Is your feature request related to a problem? Please describe.**

We're trying to use MainWP for a very large number of child sites (1k+ minimum) and are hitting "performance" issues: some operation take too long to finish despite increasing the number of simultaneous requests via the settings panel.

Example: adding a user to 100 sites takes roughly 50s

**Describe the solution you'd like**

I believe the issue comes from the hardcoded value of 10 for `mainwp_fetch_urls_chunk_size` which induces a `sleep( 5 )` for each loop, [here](https://github.com/mainwp/mainwp/blob/master/class/class-mainwp-connect.php#L657). IMHO this should probably be available for easy customization.

After a very quick glance at the rest of the code it's highly possible other similar chunked-loops could benefit from easy tweaking as well.

**Describe alternatives you've considered**

- Maye the chunk size could follow the max simultaneous requests from settings
- Maybe the sleep could be reduced and/or removed

**Additional context**

Maybe there's a valid reason for that 10-sized chunked loop but i'm having a hard time understanding it, moreover I could only go back to commit 0cbcb9d013bb21d5c88fba9088de5e94a45e10f7 without finding any sort of justification for that limit

**Comment by kun18911** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by bogdan-mainwp** [comment]
Hi @sixela, thanks for your patience.

I just checked the like you referenced and noticed that the chunk size is not hard-coded to 10. 10 is set as default value, but you can use the `mainwp_fetch_urls_chunk_size` filter to change that value on your setup. Have  you tried that?

thanks

**Comment by bogdan-mainwp** [comment]
Hi @sixela, apologies for the delay on my end one more time.
I believe that the dev team implemented chunks and delays as a common practice when processing multiple requests in order to prevent issues on lower-end hosts.
