### ISSUE TITLE
Site access button change

### ISSUE THREAD

**Issue by mariano-chomicki-sf** [mainwp/mainwp#717]
**Is your feature request related to a problem? Please describe.**
No. I just think, as an "every day" user of the plugin, that this layout would be much more convenient

**Describe the solution you'd like**
Re-organizing the cards layout of the managed websites like this:

![Screenshot 2024-11-27 at 10 36 57](https://github.com/user-attachments/assets/487473b8-e89a-4008-9016-4f06af7ef346)

**Describe alternatives you've considered**
I opted for adding the link to access the back of WP through a button on top of the "Sync Site" one

**Comment by bogdan-mainwp** [comment]
Hi @mariano-chomicki-sf, thanks for reaching out and my apologies for the small delay. 
All feature requests are welcome at [MainWP Voice](https://voice.mainwp.com), please feel free to join us there and post your suggestions.
