### ISSUE TITLE
[i18n] improvements

### ISSUE THREAD

**Issue by pedro-mendonca** [mainwp/mainwp#72]
**MainWP Dashboard** have some *i18n* issues that I'll try to describe below to further solve.
These suggestions improve consistency of the UI and reduce the number of translations strings.

- [x] Add missing Gettext functions

- [x] Add missing textdomains in existing Gettext functions

- [ ] Merge very similar strings to improve consistency
- `Add new site`, `Add New Site`

- [ ] Remove UPPERCASE strings and merge with normal ones, UPPERCASE can be done with CSS.
- `WEEKLY`, `Weekly`

- [ ] Remove double spaces in strings

- [ ] Merge strings that have different punctuation
- `Site URL`, `Site URL:`
- `Thank You`, `Thank You!`

- [ ] Concatenate strings to complete sentences - this improves understanding the context for translation
- `__( 'File has an invalid extension, it should be one of ', 'mainwp' ) . $these . '.' )` -> `sprintf( __( 'File has an invalid extension, it should be one of %s.', 'mainwp' ), $these ) )`

- [ ] Remove unnecessary spaces from beginning and end of translation strings

- [ ] Remove unnecessary HTML tags from translation strings
- `<p>No websites to scan.</p>` -> `No websites to scan.`

- [x] Align to bottom the Setup Wizard steps, it's not aligned if translations have more than one line
![screenshot 2017-09-19 11 33 43](https://user-images.githubusercontent.com/7371591/30588411-7c8c7f36-9d2e-11e7-9f01-9171b489eb09.png)

**Comment by bogdan-mainwp** [comment]
Scheduled for the next major point release.

**Comment by bogdan-mainwp** [comment]
Hi @pedro-mendonca, reported problems are solved with version 4 release. 

For any further assistence, please feel free to open a [helpdesk ticket](https://mainwp.com/my-account/get-support/).

**Comment by pedro-mendonca** [comment]
Thanks @bogdan-mainwp :)
