### ISSUE TITLE
Child Site Search in backend sidebar menu is case sensitive

### ISSUE THREAD

**Issue by phalancs** [mainwp/mainwp#73]
When searching for a child site in the backend sidebar, the filter is case sensitive which is pretty annoying. 

Maybe you should consider making it less sensitive and btw. putting a child search field up in the top admin bar instead of an additional admin footer would be a big win too :)

**Comment by bogdan-mainwp** [comment]
Scheduled for the next major point release.

**Comment by bogdan-mainwp** [comment]
Problem solved in version 4.0.
