### ISSUE TITLE
Removing admin menu items leaves links in header menu

### ISSUE THREAD

**Issue by robwent** [mainwp/mainwp#76]
Removing the posts, pages, media (etc) menu items in the admin still leaves the options in the header menu:

![mainwp-admin-header](https://user-images.githubusercontent.com/411678/32038669-e8393b5a-ba22-11e7-85d7-16c987a33cd9.PNG)

Not particularly a problem but seems to make sense to remove it there if the option isn't in the main navigation.

I'm new to mainwp so would take me a while to figure out where it should go and send a pull, but I have done something similar in the past with a site that didn't need a blog if it helps:

```
//Remove the posts menu item if the site doesn't need a blog
function post_remove () {
   remove_menu_page('edit.php');
}
add_action('admin_menu', 'post_remove');

//Also remove the new post and other links from the adminbar
function remove_wp_nodes() {
    global $wp_admin_bar;
    $wp_admin_bar->remove_node( 'new-post' );
    $wp_admin_bar->remove_node( 'new-link' );
    $wp_admin_bar->remove_node( 'new-media' );
}
add_action( 'admin_bar_menu', 'remove_wp_nodes', 999 );
```

**Comment by bogdan-mainwp** [comment]
Thanks for the suggestion, however, this is something that each user can do if it's needed by inserting the snippet to the functions.php file of the active theme. Even though we strongly suggest using the MainWP Dashboard on a dedicated installation, some users don't do this so the top admin bar navigation would still be needed.

**Comment by robwent** [comment]
That doesn't really make sense to me.

You could hide the left hand menus by adding a snippet to your themes files as well so why have the option available in the first place?

If you switch on an option to remove links to the post edit pages then you would expect it to be removed everywhere, not just in some places. Why do half a job?

Someone not using a dedicated install likely wouldn't switch that option on in the first place.

**Comment by bogdan-mainwp** [comment]
The upcoming major point release won't have this issue so I will close this issue.
