### ISSUE TITLE
Plugin management menu not usable

### ISSUE THREAD

**Issue by oliver-graetz** [mainwp/mainwp#78]
On the *PluginsManage* page, after I select several sites and get a table of all the plugins, the menu button to select an action opens the menu behind the table and I cannot select a menu item:

![plugins-select-action](https://user-images.githubusercontent.com/4057601/35803876-b30c3380-0a75-11e8-9d37-62e4e3cfdaf6.png)

Also, this button and the one to the right of it do not adhere to the language settings of the MainWP installation. I specifically changed the user language and later the whole site language to "English (US)" to produce a screenshot in english and it didn't work. While everything else switched to english, this stayed in german (also, badly translated)!?

**Comment by oliver-graetz** [comment]
The same is true for the *ThemesManage* page but it is working on the *UserBulkManage* page.

**Comment by bogdan-mainwp** [comment]
Thanks for reaching us. We are not able to duplicate this on our test sites. Can you please open a helpdesk ticket so we can troubleshoot this?

**Comment by oliver-graetz** [comment]
Thanks for the feedback. I will try to figure out if some oher third party plugin is responsible and report back here. If not, then I will use the help desk. We are just getting started using MainWP.

**Comment by oliver-graetz** [comment]
I found the culprit. We had to make a z-index adjustment for problems with another plugin and those created this problem. Sorry to bother you for what was not a problem in MainWP.
