### ISSUE TITLE
Add sites automatically

### ISSUE THREAD

**Issue by ebartz** [mainwp/mainwp#81]
Hi there,

I have seen that there is at least some integration with wp-cli. I am trying to automate as much as possible while creating new wordpress sites.

Is there a way to add new sites to a master using the CLI or an API?

**Comment by bogdan-mainwp** [comment]
Hi, there is the `mainwp_addsite` filter that can be used for adding new sites. Here is the filter usage example:

```
//all fields: url, name, wpadmin, unique_id, groupids, ssl_verify, ssl_version, http_user, http_pass
$params = array(
   'url' => 'childsite.com',
   'name' => 'the_name',
   'wpadmin' => 'the_admin_name',
   'unique_id' => 'the_unique_id'
);
$result = apply_filters( 'mainwp_addsite', $params );
```

**Comment by ebartz** [comment]
Awesome. Thanks :)

**Comment by ianwijma** [comment]
Sorry to comment on a closed issue, But is there a way of calling a hook from CLI? I have seen idea's https://github.com/wp-cli/ideas/issues/90 but nothing concrete yet.

Are there any interests in a RP adding some more WP CLI functionalities? :smile:
