### ISSUE TITLE
[i18n] Setup Wizard timeline broken in long translated titles

### ISSUE THREAD

**Issue by pedro-mendonca** [mainwp/mainwp#82]
- [x] Align to bottom the Setup Wizard steps, it's not aligned if translations have more than one line

![screenshot 2017-09-19 11 33 43](https://user-images.githubusercontent.com/7371591/30588411-7c8c7f36-9d2e-11e7-9f01-9171b489eb09.png)

Mentioned in https://github.com/mainwp/mainwp/issues/72

**Comment by bogdan-mainwp** [comment]
Fixed and it will be included in the next release.
