### ISSUE TITLE
MainWP Setup Wizard refers to Select2 CSS from wrong folder

### ISSUE THREAD

**Issue by luke-au** [mainwp/mainwp#85]
I noticed a 404 on a CSS file for Select2, code in the Setup Wizard is enqueuing a CSS file from the JS folder of select2.

> /wp-admin/admin.php?page=mainwp-setup&step=install_extension&mwp-setup=

https://github.com/mainwp/mainwp/blob/278badde5aafa65ac43675bc44ba9db077533607/page/page-mainwp-setup-wizard.php#L141

I assume that should be linking to `mainwp/js/select2/css/select2.css` rather than `mainwp/js/select2/select2.css`

**Comment by cfoellmann** [comment]
@bogdan-mainwp it would be great if you guys could invest a little bit more time into the fixes provided by you users here (e.g. pull requests)

**Comment by bogdan-mainwp** [comment]
@cfoellmann the issue has been fixed and it will be included in the next release.
