### ISSUE TITLE
running as must-use plugin kills the install

### ISSUE THREAD

**Issue by cfoellmann** [mainwp/mainwp#86]
When I put the plugin in `mu-plugins` it gives me the wizard and afterward it kills the whole WP install.
Can anyone confirm this?

It would be great if I could put everything as must-use.

**Comment by bogdan-mainwp** [comment]
Scheduled for the next major point release.

**Comment by bogdan-mainwp** [comment]
Can you try to put the `mu-mainwp-child.php` to the `mu-plugins` and see how it goes.
[mu-mainwp-child.zip](https://github.com/mainwp/mainwp/files/4782412/mu-mainwp-child.zip)
