### ISSUE TITLE
DISALLOW_FILE_MODS blocks functionality

### ISSUE THREAD

**Issue by cfoellmann** [mainwp/mainwp#90]
When I do `define( 'DISALLOW_FILE_MODS', true );` on my dashboard installation I can not install plugins on child sites.
The option "Install this Plugin" is missing.

The constant should not block features concerning remote actions. Until this can be fixed it should be tested on the "Server Information" page.

**Comment by bogdan-mainwp** [comment]
fixed, it will be included in the next release.
