### ISSUE TITLE
Some sites in list are not visible - blank

### ISSUE THREAD

**Issue by gingerling** [mainwp/mainwp#93]
Hi, not sure what to make of this -

Some sites in my list of sites are not showing in the list, there is just blank space with a check box. There dosn't seem to be any text there, it's not just gone white or something. I am using firefox browser and "Currently managing 15 child sites with MainWP 3.4.9 version"

![screenshot from 2018-08-20 13-49-21](https://user-images.githubusercontent.com/2853040/44341646-6ca01600-a480-11e8-9e68-54b4bef9160b.png)
![screenshot from 2018-08-20 13-52-34](https://user-images.githubusercontent.com/2853040/44341647-6ca01600-a480-11e8-8259-5adf32acdd48.png)

**Comment by bogdan-mainwp** [comment]
Please feel free to open a [helpdesk ticket](https://mainwp.com/my-account/get-support/) so we can help with troubleshooting.

**Comment by gingerling** [comment]
Hi, I think this clearly a bug report not troubleshooting or support.
Please get the developers to take a look. Guess it's a css issue.

**Comment by bogdan-mainwp** [comment]
It is not a CSS issue. It's an issue with escaping HTML that has been fixed a few versions ago, however, I am not sure why it's still present for you so I need you to open a helpdesk ticket so we can troubleshoot this.
