### ISSUE TITLE
SQL error

### ISSUE THREAD

**Issue by soktherat** [mainwp/mainwp#98]
In class/class-mainwp-db.php SQL queries with "groups" keyword cause problems on my MySQL serwer. Solution - "".

SELECT wp.*,wp_sync.*,wp_optionview.*, GROUP_CONCAT(gr.name ORDER BY gr.name SEPARATOR ", ") as "groups"

**Comment by bogdan-mainwp** [comment]
Hi @soktherat, this problem should be solved in one of the previous versions. 

For any further assistance, please feel free to open a [helpdesk ticket](https://mainwp.com/my-account/get-support/).
