### ISSUE TITLE
Check site HTTP response after update  

### ISSUE THREAD

**Issue by humazed** [mainwp/mainwp#99]
`Check site HTTP response after update` doesn't save its state after refreshing the page.

![image](https://user-images.githubusercontent.com/8838182/58042054-f0834d80-7b39-11e9-8f34-0760edda88f5.png)

**Comment by bogdan-mainwp** [comment]
The problem should be solved in version 4.0. If you can still reproduce the bug with the latest version, please feel free to open a [helpdesk ticket](https://mainwp.com/support/).
